import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import { fsdPlugin } from "./tooling/eslint/fsdBoundaries";
import { i18nPlugin } from "./tooling/eslint/logicalProperties";
import { securityPlugin } from "./tooling/eslint/noDangerousHtml";

/**
 * Files permitted to parse a string as HTML.
 *
 * This list is the XSS boundary, and it is here rather than in a disable
 * comment on purpose: widening it is a change to the lint configuration, which
 * a reviewer reads as one, where a `// eslint-disable-next-line` is a line in
 * whichever diff happened to need it. `docs/xss.md` explains what a file has to
 * guarantee to earn a place here. Adding one without a sanitiser is how the ban
 * becomes paperwork.
 */
const HTML_SANITISATION_BOUNDARY = ["src/shared/ui/RichText.tsx"];

export default defineConfig(
  // eslint.config.ts is excluded from the tsconfig projects (the `globals`
  // package ships no type declarations, which breaks `tsc -b`), so type-aware
  // linting cannot resolve it either.
  globalIgnores([
    "dist",
    "coverage",
    "playwright-report",
    ".tsbuildinfo",
    "eslint.config.ts",
    // Generated by `msw init`
    "public/mockServiceWorker.js",
  ]),
  {
    extends: [js.configs.recommended, tseslint.configs.strictTypeChecked],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      fsd: fsdPlugin,
      i18n: i18nPlugin,
      security: securityPlugin,
    },
    rules: {
      // The React Compiler's own diagnostics, shipped as lint rules by
      // `eslint-plugin-react-hooks` v6+ (the separate
      // `eslint-plugin-react-compiler` package was folded into this one).
      //
      // These are what make the compiler rollout safe rather than hopeful:
      // `annotation` mode means a file is only compiled once it opts in, and
      // these rules are how you find out whether a file *can* opt in before
      // adding the directive. A component that lints clean here is one the
      // compiler can memoize; one that does not is telling you about a real
      // Rules of React violation, which is a bug with or without the compiler.
      //
      // `recommended-latest` is the superset (it adds `void-use-memo`). The
      // `flat` namespace is the flat-config shape; the top-level
      // `configs.recommended` is still the legacy eslintrc export.
      ...reactHooks.configs.flat["recommended-latest"].rules,
      // Provider components live alongside their consumer hook by design; the
      // hook is stable across edits so fast refresh is unaffected.
      "react-refresh/only-export-components": [
        "warn",
        {
          allowConstantExport: true,
          allowExportNames: [
            "useToast",
            "useAuth",
            "useTheme",
            "useRouteTransition",
            "useRoutePrefetch",
            "useI18n",
          ],
        },
      ],
      // The Feature-Sliced Design boundary. Only meaningful under `src/`; the
      // rule returns immediately for anything outside it, so it costs nothing
      // to leave on for `e2e/` and the config files.
      //
      // It leans on `consistent-type-imports` below: the exemption for
      // type-only imports is only sound if a type-only import is *spelled* as
      // one, and that rule is what makes an inline `import { RootState }`
      // impossible to write.
      "fsd/layer-imports": "error",
      // The right-to-left layout pass, enforced rather than reviewed. A
      // physical `ml-4` is invisible to every other gate here: it type-checks,
      // it renders, and axe has no opinion about which side a margin is on. See
      // `tooling/eslint/logicalProperties.ts`.
      "i18n/logical-properties": "error",
      // The XSS boundary, enforced rather than reviewed. React escapes every
      // interpolated string, so the only way markup reaches the DOM here is
      // through a sink that parses it — and every one of those is reported
      // outside `HTML_SANITISATION_BOUNDARY`. See
      // `tooling/eslint/noDangerousHtml.ts` for the list of sinks and
      // `docs/xss.md` for the policy they leave as the only route.
      "security/no-dangerous-html": ["error", { allow: HTML_SANITISATION_BOUNDARY }],
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      // Interpolating a number is safe and universally readable; the default
      // ban on it produces noise without catching real defects.
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
      // JSX event handlers are fire-and-forget by design. Promise-returning
      // handlers still matter elsewhere, so only the attribute check is off.
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
    },
  },
  {
    // Tests assert on values the type system cannot narrow (query results,
    // captured request bodies). Non-null assertions are the clearest tool there.
    files: ["**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
    rules: {
      // Test scaffolding is not in the fast-refresh graph: nothing under
      // `src/test/` is rendered by the application, so a harness that exports a
      // wrapper component beside the helpers it needs costs nothing.
      "react-refresh/only-export-components": "off",
      // A test that builds a DOM fixture out of a string it wrote itself —
      // `focusTrap.test.ts` is the one here — is not an injection: there is no
      // untrusted input anywhere in a unit test, and nothing in a `.test.` file
      // is in the shipped module graph (`fsd/layer-imports` guarantees the
      // second half of that). The ban is about code that renders data, so it is
      // scoped to the code that can receive data.
      "security/no-dangerous-html": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/unbound-method": "off",
    },
  },
  {
    // Playwright's `use` fixture callback is not a React hook; the
    // rules-of-hooks heuristic matches on the name alone.
    files: ["e2e/**/*.ts", "playwright.config.ts"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
    },
  },
  {
    // RTK Query spells "this endpoint takes no argument" as `void`
    // (`builder.mutation<void, void>`). The rule only honours
    // allowInGenericTypeArguments for type references, not for type arguments
    // on a call expression, so it misfires on every endpoint definition.
    files: ["**/*Api.ts"],
    rules: {
      "@typescript-eslint/no-invalid-void-type": "off",
    },
  },
  {
    // The `globals` package ships untyped global maps.
    files: ["eslint.config.ts"],
    rules: {
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },
);
