import { http, HttpResponse } from "msw";
// Type-only, and so exempt from the import-boundary rule's layer order: it is
// erased before a module graph exists. The point of naming the real type here
// is that a change to `Post` fails the type check in the mock that claims to
// serve one, rather than leaving the mock quietly describing something else.
import type { Post } from "@/entities/post/postsApi";

const API = "http://localhost:4000";

export const authHandlers = [
  http.post(`${API}/auth/login`, () =>
    HttpResponse.json({
      token: "mock-access-token",
      refreshToken: "mock-refresh-token",
      expiresIn: 900,
      user: { id: "1", email: "test@example.com", role: "user" },
    }),
  ),
  http.post(`${API}/auth/refresh`, () =>
    HttpResponse.json({ token: "mock-refreshed-token", expiresIn: 900 }),
  ),
  http.post(`${API}/auth/logout`, () => new HttpResponse(null, { status: 200 })),
  http.get(`${API}/auth/me`, () =>
    HttpResponse.json({ id: "1", email: "test@example.com", role: "user" }),
  ),
  http.post(`${API}/auth/google/callback`, () =>
    HttpResponse.json({
      token: "google-access-token",
      refreshToken: "google-refresh-token",
      expiresIn: 3600,
      user: { id: "2", email: "google@example.com", role: "user" },
    }),
  ),
];

export const postHandlers = [
  http.get(`${API}/posts`, () =>
    HttpResponse.json([
      { id: 1, title: "First Post", body: "Content one", userId: 1 },
      { id: 2, title: "Second Post", body: "Content two", userId: 1 },
    ]),
  ),
  http.get(`${API}/posts/:id`, ({ params }) => {
    // A path param is typed as string | readonly string[] because a pattern can
    // match repeated segments; this route only ever binds a single value.
    const id = Number(params["id"]);
    return HttpResponse.json({
      id,
      title: `Post ${id}`,
      body: "Post body content",
      userId: 1,
    });
  }),
  http.post(`${API}/posts`, async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({ id: 100, ...body }, { status: 201 });
  }),
  http.put(`${API}/posts/:id`, async ({ params, request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({ id: Number(params["id"]), ...body });
  }),
  http.delete(`${API}/posts/:id`, () => new HttpResponse(null, { status: 204 })),
];

/** Rows the mock feed holds. Large enough that windowing is the only way. */
export const FEED_TOTAL = 5_000;

/** The mock feed's rows are a pure function of their index. */
function makeFeedItem(index: number): Post {
  return {
    id: index + 1,
    title: `Feed item ${index + 1}`,
    body: `Body for feed item ${index + 1}, generated by the mock server.`,
    userId: (index % 10) + 1,
  };
}

export const feedHandlers = [
  /**
   * Cursor-paginated feed backing `/labs/infinite-scroll`.
   *
   * The cursor is the index of the first row of the *next* page, as a string.
   * Opaque to the client by contract — `useInfiniteFeed` only ever echoes it
   * back — which is what lets it stay a number here and become a keyset
   * predicate against a real database without the client changing.
   */
  http.get(`${API}/feed`, ({ request }) => {
    const url = new URL(request.url);
    const requestedLimit = Number(url.searchParams.get("limit") ?? 50);
    const limit = Number.isFinite(requestedLimit)
      ? Math.min(Math.max(Math.trunc(requestedLimit), 1), 200)
      : 50;
    const requestedCursor = Number(url.searchParams.get("cursor") ?? 0);
    const start = Number.isFinite(requestedCursor)
      ? Math.min(Math.max(Math.trunc(requestedCursor), 0), FEED_TOTAL)
      : 0;

    const end = Math.min(start + limit, FEED_TOTAL);
    return HttpResponse.json({
      items: Array.from({ length: end - start }, (_, i) => makeFeedItem(start + i)),
      nextCursor: end < FEED_TOTAL ? String(end) : null,
      total: FEED_TOTAL,
    });
  }),
];

export const handlers = [...authHandlers, ...postHandlers, ...feedHandlers];
